sonar.projectKey=bolorundurovj_LagosFile
sonar.organization=bolorundurovj

sonar.projectName=LagosFile
sonar.projectVersion=1.0.0

# Paths
sonar.sources=src,extension/chrome,extension/firefox,src-tauri/src
sonar.exclusions=src-tauri/target/**,node_modules/**,dist/**,dist-ext/**

# TypeScript / JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

# Rust
sonar.rust.cargoManifestPath=src-tauri/Cargo.toml

# Encoding
sonar.sourceEncoding=UTF-8
