use crate::AppState;
use rusqlite::params;
use tauri::State;

#[tauri::command]
pub async fn export_filing_pdf(
    filing_id: String,
    _include_attachments: bool,
    state: State<'_, AppState>,
) -> Result<String, String> {
    let guard = state.db.lock().map_err(|e| e.to_string())?;
    let db = guard.as_ref().ok_or("Database not unlocked")?;
    let conn = db.conn.lock().map_err(|e| e.to_string())?;

    let filing: serde_json::Value = conn.query_row(
        "SELECT f.filing_reference, f.year_of_assessment, f.final_tax_payable,
                t.full_name, t.tin
         FROM filing f JOIN taxpayer t ON t.id = f.taxpayer_id
         WHERE f.id = ?1",
        params![filing_id],
        |row| {
            Ok(serde_json::json!({
                "reference": row.get::<_,Option<String>>(0)?,
                "yoa": row.get::<_,i32>(1)?,
                "finalTax": row.get::<_,Option<f64>>(2)?,
                "name": row.get::<_,String>(3)?,
                "tin": row.get::<_,String>(4)?,
            }))
        },
    ).map_err(|e| e.to_string())?;

    // Build a simple CSV/text export (full PDF rendering requires a PDF crate; here we output
    // a structured text file the user can open or print)
    let home = dirs::home_dir().unwrap_or_else(|| std::path::PathBuf::from("."));
    let out_dir = home.join("LagosFile").join("exports");
    std::fs::create_dir_all(&out_dir).map_err(|e| e.to_string())?;

    let filename = format!(
        "LagosFile_{}_{}.txt",
        filing["reference"].as_str().unwrap_or(&filing_id),
        filing["yoa"].as_i64().unwrap_or(0)
    );
    let out_path = out_dir.join(&filename);

    let content = format!(
        "LAGOSFILE TAX COMPUTATION STATEMENT\n\
         =====================================\n\
         Taxpayer: {}\n\
         TIN: {}\n\
         Year of Assessment: {}\n\
         Filing Reference: {}\n\
         Final Tax Payable: NGN {:.2}\n\
         =====================================\n\
         Generated by LagosFile v2.0 (Angular + Tauri)\n\
         LIRS Direct Assessment — NTA 2025\n",
        filing["name"].as_str().unwrap_or(""),
        filing["tin"].as_str().unwrap_or(""),
        filing["yoa"].as_i64().unwrap_or(0),
        filing["reference"].as_str().unwrap_or("—"),
        filing["finalTax"].as_f64().unwrap_or(0.0),
    );
    std::fs::write(&out_path, &content).map_err(|e| e.to_string())?;
    Ok(out_path.to_string_lossy().to_string())
}

#[tauri::command]
pub async fn export_filing_csv(
    filing_id: String,
    state: State<'_, AppState>,
) -> Result<String, String> {
    let guard = state.db.lock().map_err(|e| e.to_string())?;
    let db = guard.as_ref().ok_or("Database not unlocked")?;
    let conn = db.conn.lock().map_err(|e| e.to_string())?;

    let mut stmt = conn.prepare(
        "SELECT income_type,description,gross_amount_ngn,is_foreign,foreign_currency,
                foreign_amount,income_date,fx_rate_fetched,fx_rate_cbn_override,
                fx_rate_used,fx_rate_source
         FROM income_entry WHERE filing_id=?1"
    ).map_err(|e| e.to_string())?;

    let mut csv = String::from(
        "income_type,description,gross_amount_ngn,is_foreign,foreign_currency,\
         foreign_amount,income_date,fx_rate_fetched,fx_rate_cbn_override,fx_rate_used,fx_rate_source\n"
    );
    stmt.query_map(params![filing_id], |row| {
        Ok(format!(
            "{},{},{},{},{},{},{},{},{},{},{}\n",
            row.get::<_,String>(0)?,
            row.get::<_,Option<String>>(1)?.unwrap_or_default(),
            row.get::<_,f64>(2)?,
            row.get::<_,i32>(3)?,
            row.get::<_,Option<String>>(4)?.unwrap_or_default(),
            row.get::<_,Option<f64>>(5)?.map_or(String::new(), |v| v.to_string()),
            row.get::<_,Option<String>>(6)?.unwrap_or_default(),
            row.get::<_,Option<f64>>(7)?.map_or(String::new(), |v| v.to_string()),
            row.get::<_,Option<f64>>(8)?.map_or(String::new(), |v| v.to_string()),
            row.get::<_,Option<f64>>(9)?.map_or(String::new(), |v| v.to_string()),
            row.get::<_,Option<String>>(10)?.unwrap_or_default(),
        ))
    }).map_err(|e| e.to_string())?
    .filter_map(|r| r.ok())
    .for_each(|line| csv.push_str(&line));

    let home = dirs::home_dir().unwrap_or_else(|| std::path::PathBuf::from("."));
    let out_path = home.join("LagosFile").join("exports").join(format!("filing_{}.csv", &filing_id[..8]));
    std::fs::create_dir_all(out_path.parent().unwrap()).map_err(|e| e.to_string())?;
    std::fs::write(&out_path, &csv).map_err(|e| e.to_string())?;
    Ok(out_path.to_string_lossy().to_string())
}

#[tauri::command]
pub async fn export_filing_json(
    filing_id: String,
    state: State<'_, AppState>,
) -> Result<String, String> {
    let guard = state.db.lock().map_err(|e| e.to_string())?;
    let db = guard.as_ref().ok_or("Database not unlocked")?;
    let conn = db.conn.lock().map_err(|e| e.to_string())?;

    let filing: serde_json::Value = conn.query_row(
        "SELECT id,year_of_assessment,status,filing_reference,created_at,confirmed_at,
                total_income_ngn,chargeable_income,final_tax_payable,tax_config_version
         FROM filing WHERE id=?1",
        params![filing_id],
        |row| {
            Ok(serde_json::json!({
                "id": row.get::<_,String>(0)?,
                "yearOfAssessment": row.get::<_,i32>(1)?,
                "status": row.get::<_,String>(2)?,
                "filingReference": row.get::<_,Option<String>>(3)?,
                "createdAt": row.get::<_,String>(4)?,
                "confirmedAt": row.get::<_,Option<String>>(5)?,
                "totalIncomeNgn": row.get::<_,Option<f64>>(6)?,
                "chargeableIncome": row.get::<_,Option<f64>>(7)?,
                "finalTaxPayable": row.get::<_,Option<f64>>(8)?,
                "taxConfigVersion": row.get::<_,String>(9)?,
            }))
        },
    ).map_err(|e| e.to_string())?;

    let json = serde_json::to_string_pretty(&filing).map_err(|e| e.to_string())?;
    let home = dirs::home_dir().unwrap_or_else(|| std::path::PathBuf::from("."));
    let out_path = home.join("LagosFile").join("exports").join(format!("filing_{}.json", &filing_id[..8]));
    std::fs::create_dir_all(out_path.parent().unwrap()).map_err(|e| e.to_string())?;
    std::fs::write(&out_path, &json).map_err(|e| e.to_string())?;
    Ok(out_path.to_string_lossy().to_string())
}
