"""
Property-based tests for the PIN-keyed Fernet encryption module.

Property 25: Encryption round-trip
  - decrypt_db(encrypt_db(data, key), key) == data for any bytes and any PIN
  - Decrypting with a different PIN raises InvalidToken

Validates: Requirements 14.1, 14.3, 14.4
# Feature: lagos-file, Property 25: Encryption round-trip
"""

import hypothesis.strategies as st
from hypothesis import given, settings
from cryptography.fernet import InvalidToken

from lagosfile.security import derive_key, encrypt_db, decrypt_db, generate_salt


# Reusable strategy: a random salt (16 bytes, as generated by generate_salt)
salt_strategy = st.binary(min_size=16, max_size=16)

# PIN strategy: 4–8 digit strings (realistic PINs)
pin_strategy = st.text(min_size=4, max_size=8, alphabet="0123456789")


@given(
    data=st.binary(min_size=1, max_size=4096),
    pin=pin_strategy,
    salt=salt_strategy,
)
@settings(max_examples=25, deadline=None)
def test_encryption_round_trip(data: bytes, pin: str, salt: bytes) -> None:
    """Property 25 (part 1): decrypt_db(encrypt_db(data, key), key) == data.

    For any plaintext bytes, any PIN, and any salt, encrypting then decrypting
    with the same derived key must return the original bytes.

    Validates: Requirements 14.1, 14.3, 14.4
    """
    key = derive_key(pin, salt)
    encrypted = encrypt_db(data, key)
    decrypted = decrypt_db(encrypted, key)
    assert decrypted == data


@given(
    data=st.binary(min_size=1, max_size=1024),
    pin1=pin_strategy,
    pin2=pin_strategy,
    salt=salt_strategy,
)
@settings(max_examples=25, deadline=None)
def test_wrong_pin_raises_invalid_token(
    data: bytes, pin1: str, pin2: str, salt: bytes
) -> None:
    """Property 25 (part 2): decrypting with a different PIN raises InvalidToken.

    For any two distinct PINs, the key derived from pin2 must not successfully
    decrypt data encrypted with the key derived from pin1.

    Validates: Requirements 14.3, 14.4
    """
    if pin1 == pin2:
        return  # same PIN → same key → would succeed; skip

    key1 = derive_key(pin1, salt)
    key2 = derive_key(pin2, salt)

    encrypted = encrypt_db(data, key1)

    try:
        decrypt_db(encrypted, key2)
        raise AssertionError(
            f"Expected InvalidToken when decrypting with wrong PIN "
            f"(pin1={pin1!r}, pin2={pin2!r})"
        )
    except InvalidToken:
        pass  # expected


# ---------------------------------------------------------------------------
# Unit tests for supporting functions
# ---------------------------------------------------------------------------

def test_generate_salt_returns_16_bytes() -> None:
    """generate_salt() must return exactly 16 bytes."""
    salt = generate_salt()
    assert isinstance(salt, bytes)
    assert len(salt) == 16


def test_generate_salt_is_random() -> None:
    """Two calls to generate_salt() should (almost certainly) differ."""
    assert generate_salt() != generate_salt()


def test_derive_key_returns_fernet_compatible_key() -> None:
    """derive_key() must return a URL-safe base64-encoded 44-character string."""
    import base64
    salt = generate_salt()
    key = derive_key("1234", salt)
    # Fernet keys are 32 bytes encoded as URL-safe base64 → 44 chars with padding
    decoded = base64.urlsafe_b64decode(key)
    assert len(decoded) == 32


def test_derive_key_same_inputs_same_output() -> None:
    """derive_key() is deterministic: same PIN + salt → same key."""
    salt = generate_salt()
    assert derive_key("5678", salt) == derive_key("5678", salt)


def test_derive_key_different_salts_different_keys() -> None:
    """Different salts must produce different keys for the same PIN."""
    salt1 = generate_salt()
    salt2 = generate_salt()
    # Extremely unlikely to collide
    assert derive_key("1234", salt1) != derive_key("1234", salt2)




